FROM --platform=$BUILDPLATFORM golang:alpine AS build

WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
# Binary Compression
RUN apk upgrade --no-cache && apk add upx --no-cache

# Build app and pack using upx
ADD . /app
ARG TARGETOS
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags '-s -w -X main.VERSION=docker' -o gohttpserver && upx gohttpserver

FROM alpine:3
WORKDIR /app
ADD assets /usr/local/bin/assets
COPY --from=build /app/gohttpserver /usr/local/bin/gohttpserver
EXPOSE 8000
ENTRYPOINT [ "/usr/local/bin/gohttpserver" , "--root=/app/public"]
